### ISSUE TITLE
No Tags in SVG

### ISSUE THREAD

**Issue by J2ch** [riclolsen/scadavis#4]
Hi, I just tried the first demo on the Leran-Page of the Homepage (with the donut.svg) and added the line to print in the browser console the taglsit of the svg. Unfortunately it always prints "undefined" and not "TAG1" as it should, if I understand it right. Any help?

**Comment by riclolsen** [comment]
This will print the list of tags found in the SVG file:
        
        // create a new graphic
        scadavisInit( { 
          svgurl: "https://raw.githubusercontent.com/riclolsen/displayfiles/master/donut.svg"
        }).then( sv => {
          console.log(sv.getTagsList()); // <<<<<<<<<<<<<<<<<
          // update value in the graphic at each 1.5 seconds
          setInterval( function() {
          sv.setValue("TAG1", Math.random()*100); 
          if (sv.getValue("TAG1") >= 75)
            sv.setValue("TAG2", "alarmed!"); 
          else  
            sv.setValue("TAG2", "normal"); 
          },1500); 
        })
